### ISSUE TITLE
Error while preprocessing (...).md - No grammar provided for <source.shell>

### ISSUE THREAD

**Issue by KraXen72** [antfu/shikiji#25]
### Describe the bug

When using with SvelteKit, MDSveX and the shikiji package, it all works well and pre-processes the files.
But, when i go to pre-process a sh codeblock, it throws an error.
i am trying to dynamically load the lanugages, which works, but not for sh. i also tried to specify sh in `langs`, but it still threwt he error.
this is my `mdsvex.config.js`

```js
import rehypeSlug from 'rehype-slug';
import rehypeAutolinkHeadings from 'rehype-autolink-headings';
import rehypeExternalLinks from 'rehype-external-links';
import remarkFootnotes from 'remark-footnotes';
import { defineMDSveXConfig as defineConfig, escapeSvelte } from 'mdsvex';
import { getHighlighter } from 'shikiji'

// add any frequently used languages here
const langs = ['javascript', 'typescript', 'jsx', 'tsx', 'svelte', 'html', 'css', 'json', 'python']
const shiki = await getHighlighter({
	langs,
	themes: ['vitesse-light', 'vitesse-dark']
})

async function mdsvexShikijiHighlighter(code, lang) {
	try {
		if (!langs.includes(lang)) {
			await shiki.loadLanguage(lang)
			langs.push(lang)
		}
		const html = shiki.codeToHtml(code, {
			lang,
			themes: {
				light: 'vitesse-light',
				dark: 'vitesse-dark'
			}
		})
		return `{@html \`${escapeSvelte(html)}\`}`
	} catch(e) {
		return code
	}
	
}

const config = defineConfig({
	extensions: ['.svelte.md', '.md', '.svx'],
	smartypants: { dashes: 'oldschool' },
	highlight: { highlighter: mdsvexShikijiHighlighter },
	remarkPlugins: [ remarkFootnotes ],
	rehypePlugins: [
		[ rehypeExternalLinks, { target: '_blank', rel: ['nofollow', 'noreferrer'] }],
		rehypeSlug,
		[ rehypeAutolinkHeadings, { behavior: 'prepend',  } ]
	],
});

export default config;
```

full error:
```
Error: Error while preprocessing D:/coding/svelte/pursiny-sveltekit/posts/dillinger-kitchen-sink 2023-10-25.md - No grammar provided for <source.shell>\n' +
        '    at a (file:///D:/coding/svelte/pursiny-sveltekit/node_modules/.pnpm/shikiji@0.6.10/node_modules/shikiji/dist/core.mjs:413:15520)\n' +
        '    at t.ScopeDependencyProcessor.processQueue (file:///D:/coding/svelte/pursiny-sveltekit/node_modules/.pnpm/shikiji@0.6.10/node_modules/shikiji/dist/core.mjs:413:17212)\n' +
        '    at Registry._loadGrammar (file:///D:/coding/svelte/pursiny-sveltekit/node_modules/.pnpm/shikiji@0.6.10/node_modules/shikiji/dist/core.mjs:413:30884)\n' +
        '    at async Registry.loadLanguage (file:///D:/coding/svelte/pursiny-sveltekit/node_modules/.pnpm/shikiji@0.6.10/node_modules/shikiji/dist/core.mjs:522:15)\n' +
        '    at async Registry.loadLanguages (file:///D:/coding/svelte/pursiny-sveltekit/node_modules/.pnpm/shikiji@0.6.10/node_modules/shikiji/dist/core.mjs:546:7)\n' +
        '    at async Object.loadLanguage (file:///D:/coding/svelte/pursiny-sveltekit/node_modules/.pnpm/shikiji@0.6.10/node_modules/shikiji/dist/core.mjs:647:5)\n' +
        '    at async mdsvexShikijiHighlighter (file:///D:/coding/svelte/pursiny-sveltekit/mdsvex.config.js:17:3)\n' +
        '    at async D:\\coding\\svelte\\pursiny-sveltekit\\node_modules\\.pnpm\\mdsvex@0.11.0_svelte@4.2.2\\node_modules\\mdsvex\\dist\\main.cjs.js:25745:19\n' +
        '    at async Promise.all (index 0)\n' +
        '    at async D:\\coding\\svelte\\pursiny-sveltekit\\node_modules\\.pnpm\\mdsvex@0.11.0_svelte@4.2.2\\node_modules\\mdsvex\\dist\\main.cjs.js:25742:4
```

### Reproduction

the repository is private. This should be reproducible anywhere, as it appears to have a missing grammar. if it's not, let me know, and i'll provide a repro.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 11.99 GB / 23.88 GB
  Binaries:
    Node: 19.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.61)
    Internet Explorer: 11.0.19041.3570
    Vivaldi 6.2.3105.58 (Stable channel) (64-bit) (wasn't recognized, primary browser)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ajitzero** [comment]
`sh` does not exist as a valid language key. Have you tried adding [`shellscript`](https://github.com/antfu/shikiji/blob/01328176af801f576216027986dda0d327c8134b/packages/shikiji/src/assets/langs.ts#L142C12-L142C12)?

**Comment by KraXen72** [comment]
i have migrated to the normal shiki. i don't think i tried adding shellscript

**Comment by antfu** [comment]
`sh` should work. Please provide a minimal reproduction, thanks.
